sudo: required
os: osx
osx_image: xcode11
language: node_js
node_js: "12"
matrix:
  allow_failures:
cache:
- apt: true
- yarn: true
- directories:
  - node_modules
  - "$HOME/.electron"
before_install:
- bash test/ci/before_install.sh
install:
- yarn global add codecov
- yarn
- node scripts/check-electron-version.js
script:
- yarn test
- yarn build
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: PAPFtI8FpGjP2RvXKfUUNr8dBpAoLFukGtM+kxvBAzAyXIEH1IkINrDAPm4+TuyuareuG6xPvkpdktxhoDfbO62aAUs0/KioQxQfgmIv6xzvhuv/wfBpKezL/AffAoclMWwIl1JiqZwD6SKAVBU8A2teTskQrWnKIyRXkdxrEaBrmdZWuimc5H7Lb4MaMTO6Nmmm9eU2R2Gg2bOYhgAHBxUwGvxEacunl/VdJCFQdb70lQeREHqkPJ4SiXRWolCaEF33Y9UHpOAVUeup6ERzWri2LHn5cBVWFZ3DeEJr4MN+c7GpEFRWj3C1JsZ/e5mTNmvefldrFP386JW5zeyFGWjBiWgbV5au3hRVA/y76b+t39Xor39pBLz8RJhJs9TEwaBelminirFU/bk67CQ32KmxBHJNH8MgxGmgMBB8X/JgGOLpIrMgMTeErQY8XRMFBhzma4cbJ3DAl3JBV43759AZPL7h9+4NqCqBPPOrOehDNIe//bMVRi5Rd3tDtK3eC1F+NKobTq3xYYsKqktzzSkxJ/KC4oVL58ILnCND6EQ/MZtFphfvqnVTxS+Q2Mk2dMNjv0ZakrvDi/quGlgfionCPhgRbUiiYDnxEsVNJhkVfFiv2qk0clKJhQ10OarinTedLiqf7c2qT5Kj5shJXzSYyB+1eIC4KUttQgXZNLI=
  file_glob: true
  overwrite: true
  file:
  - build/*.dmg
  - build/*.deb
  - build/*.rpm
  - build/latest-mac.yml
  - build/*.blockmap
  - build/*.zip
  skip_cleanup: true
  on:
    tags: true
after_success:
- codecov
- bash scripts/trigger-mas-dev.sh
